' Gambas module file

Public Function CambioLetras(cadena As String) As String
  
  Dim a As Integer
  Dim reemplazo, reemplazopor As String[]
  
  reemplazo = ["%C3%A1", "%C3%A9", 
    "%C3%AD",
    "%C3%B3", 
    "%C3%BA", 
    "%C3%81",
    "%C3%89", 
    "%C3%8D", 
    "%C3%93",
    "%C3%9A", 
    "%20",
    "%C3%91", 
    "%C3%B1"]
  
  reemplazopor = ["á", "é", "í", "ó", "ú", "Á", "É", "Í", "Ó", "Ú", " ", "Ñ", "ñ"]
  
  For a = 0 To reemplazo.count - 1
    cadena = Replace(cadena, reemplazo[a], reemplazopor[a])
    
  Next
  
  Return cadena
  
End
